### ISSUE TITLE
Automaticke postovanie do fora

### ISSUE THREAD

**Issue by jsuchal** [slovensko-digital/uvobot#2]
Bolo by fajn keby uvobot vedel zakladne info o zakazke vytiahnut z detailu (obstaravatel, sumu, sposob sutaze, predmet sutaze) a vytvorit na platforme k tomu automaticky topic s tymi info a odkazom na vestnik. 

Toto by malo pomoct https://github.com/discourse/discourse_api

**Comment by martinsabo** [comment]
@jsuchal Začal som to implementovať (https://github.com/martinsabo/uvobot/commit/cea5844d9e912d078b17ea1e0f6a00f356a41c4f) a narazil som na zopár úskalí, kde by bodli doplňujúce informácie, alebo konzultácia:

- Discourse ma celkom obmedzujúce nastavenia na postovanie v defaulte (frekvencia, unikatnosť, počty za deň). Treba to urobiť konfigurovateľné s umelým uspávaním, alebo sa prestaví cieľový discourse podľa potreby?

- Parsovanie detailu UVO oznamu je momentálne veľmi labilné, zatiaľ odtiaľ beriem len cenu, ale aj tam ma môžu zrušiť zmenou formátu. Tie oznamy nemajú vždy úplne rovnaký formát, bude treba odsledovať opakujúce sa vzory a implementovať nejaký pekný failback.

- Oficiálny discourse api gem, má pravdepodobne bug, na konci úspešného postu (data docestujú do discourse v pohode) to aj tak padne s JSON parsing exception. Zatiaľ ju natvrdo ignorujem. Momentálne sú tie api volania jednoduché, dal by sa napísať aj vlastný client za relatívne krátky čas.

- Kto bude kontrolovať unikátnosť topicov (napr. pri opakovanom spustení uvobota). Uvobot pred postom, alebo discourse na vstupe?

- Ako by sa to malo správať po neúspešnom pokuse o  vytvorenie topicu?

- Jeden ideový zádrhel na úrovni kódu (https://github.com/martinsabo/uvobot/blob/master/lib/discourse_publisher.rb#L2). Publisher dostane klientský objekt už hotový, ale vnútri by bolo vhodne odchytávať exception implementovanú v klientovi. Tak jej triedu tiež vkladám na vstupe. Otázka je či by sa to nedalo vyriešiť krajšie.

**Comment by martinsabo** [comment]
@jsuchal ten posledný bod je už neaktuálny. Prerobil som to.

**Comment by jsuchal** [comment]
1. Discourse prestavit neni problem.
2. Toto je oriesok. Viem ze to parsuje AFP tu https://github.com/fairplaysk/datacamp/tree/master/lib/etl/vvo_v2 neviem ci chceme ist do takeho. Nepotrebujeme to asi az tak strukturovane. Stacilo by to vytiahnut nejako a ked nenajdeme, tak len napisat do topicu, ze sa cenu nepodarilo najst.
3. Oficialny gem vyzera ze zije. Skus zareportovat ten bug.
4. Na unikatnost topicov sa zatial vykaslat.
5. Neuspesne vytvorenie topicu. Toto zatial neriesme, dajme ako issue. Akonahle budeme riesit perzistenciu tak to otvorime znova.

**Comment by martinsabo** [comment]
1. Ok
2. Ok - zatial naivny parser, co vrati prazdnu hodnotu ak padne, alebo nenajde.
3. Uz som to tusim videl aj hlasit ludi v inych projektoch so pouzivaju Faraday. Nejako je okolo toho mrtvo.
4. Discogs to vie celkom ucinne validovat, nastavil by som to aspon tam.
5. Chapem to tak ze proste pokracujem na dalsi oznam ked to padne s hocijakym discourse API exception zatial.
