### ISSUE TITLE
Neposielanie notifikacie ak nie je vestnik cez vikend

### ISSUE THREAD

**Issue by jsuchal** [slovensko-digital/uvobot#6]
Cez vikend by nas to nemuselo spamovat :)

**Comment by martinsabo** [comment]
@jsuchal Ako si to predstavujes? Predpokladam, ze cez vikend treba vyradit len slack  notifikaciu na chybajuci vestnik.

**Comment by jsuchal** [comment]
Hej, ak sa nenajde vestnik a je vikend tak to neposle notifikaciu. Keby sa nasiel a bol vestnik novy, tak ideme po starom. Easy fix.
