### ISSUE TITLE
Prechod na novy vestnik

### ISSUE THREAD

**Issue by jsuchal** [slovensko-digital/uvobot#8]
Zda sa, ze novy vestnik nam komplikuje robotu kedze odstranili XML. http://www.uvo.gov.sk/vestnik-a-zoznam-registrov/vestnik-479.html

http://www.uvo.gov.sk/vestnik/oznamenia/zoznam tu je pokrocile vyhladavanie.

**Comment by martinsabo** [comment]
Správne to chápem, že podstatou tohoto issue je prispôsobenie terajšieho Uvobota novej UVO stránke?

**Comment by jsuchal** [comment]
Ano, ale na prvy pohlad to nebude velmi boliet.

**Comment by martinsabo** [comment]
Ok. Pozriem sa na to.
