### ISSUE TITLE
Detaily obstaravania

### ISSUE THREAD

**Issue by jsuchal** [slovensko-digital/uvobot#9]
K obstaravaniu urcite chceme vediet dalsie detaily:

- druh postupu. Napriklad Rokovacie konanie bez zverejnenia je takmer vzdy zaujimave. 
- vitaz obstaravania. 'nuf said.

**Comment by martinsabo** [comment]
Tu by sa nedalo portovať know-how z parsera AFP? Či ten tiež nie je aktuálny na novej UVO stránke?

**Comment by jsuchal** [comment]
@martinsabo nie je. My to navyse nechceme tak velmi strukturovane. Kedze to len zatial plieskame do fora.

**Comment by jsuchal** [comment]
Co sa tyka detailov, potrebujeme:

trvanie projektu
druh postupu
Lehota na predkladanie ponuk

**Comment by martinsabo** [comment]
Vitaz obstaravania?

**Comment by jsuchal** [comment]
```
NÁZOV A ADRESA HOSPODÁRSKEHO SUBJEKTU, V PROSPECH KTORÉHO SA ROZHODLO O ZADANÍ ZÁKAZKY
MEDICAL GROUP SK a.s. 
Vnútroštátne identifikačné číslo: 31708030 
Trnavská cesta 27/B , 83104 Bratislava 
Slovensko 
Telefón: +421 552852215 
```

Napriklad z https://www.uvo.gov.sk/vestnik/oznamenie/detail/329328

**Comment by martinsabo** [comment]
Ok.

**Comment by martinsabo** [comment]
Stačí názov firmy, alebo treba celú adresu?

**Comment by jsuchal** [comment]
Tak idealne tak ako to tam je.
